exec-once = playerctld daemon

windowrule = float on, match:class org.omarchy.media-popup
windowrule = pin on, match:class org.omarchy.media-popup
windowrule = size 660 245, match:class org.omarchy.media-popup
windowrule = move ((monitor_w-window_w)/2) 34, match:class org.omarchy.media-popup
